export const kureTherapeuticCategories = [
  {
    name: "Anti-Cancer Medicines",
    category: "Anti-Cancer Medicines",
    slug: "anti-cancer-medicines",
    bgColor: "#FFF0F0",
    textColor: "#DC2626",
    icon: "anti-cancer",
    productCount: "320+",
    image: "/products/cancer_treatment_pack.png",
  },
  {
    name: "Oncology Drugs",
    category: "Oncology Drugs",
    slug: "oncology-drugs",
    bgColor: "#F3EEFF",
    textColor: "#7C3AED",
    icon: "oncology",
    productCount: "250+",
    image: "/products/oncology.png",
  },
  {
    name: "Critical Care Medicines",
    category: "Critical Care Medicines",
    slug: "critical-care-medicines",
    bgColor: "#FFF0F5",
    textColor: "#BE185D",
    icon: "critical-care",
    productCount: "180+",
    image: "/products/critical.png",
  },
  {
    name: "Lifesaving Drugs",
    category: "Lifesaving Drugs",
    slug: "lifesaving-drugs",
    bgColor: "#FFFBEA",
    textColor: "#D97706",
    icon: "lifesaving",
    productCount: "180+",
    image: "/products/lifesaving_emergency_box.png",
  },
  {
    name: "Imported medicine",
    category: "Imported medicine",
    slug: "imported-medicine",
    bgColor: "#EDFFF5",
    textColor: "#059669",
    icon: "imported",
    productCount: "120+",
    image: "/products/imported.png",
  },
  {
    name: "HIV",
    category: "HIV",
    slug: "hiv",
    bgColor: "#FDF2F8",
    textColor: "#DB2777",
    icon: "hiv",
    productCount: "120+",
    image: "/products/hiv.png",
  },
  {
    name: "Nephrology Medicine",
    category: "Nephrology Medicine",
    slug: "nephrology-medicine",
    bgColor: "#EFF7FF",
    textColor: "#2563EB",
    icon: "nephrology",
    productCount: "95+",
    image: "/products/nephrology.png",
  },
];

export const popularCategoryItems = kureTherapeuticCategories.map(
  ({ name, category, bgColor, textColor, icon, productCount, image }) => ({
    name,
    category,
    bgColor,
    textColor,
    icon,
    productCount,
    image,
  }),
);

export default kureTherapeuticCategories;
